kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/task-definition-config/components/Header.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/TaskCommitModal.tsx
kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/DataDiscoveryBoard.tsx
kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/FailedTestCasesTable.less
kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/FailedTestCasesTable.tsx
kun-frontend/src/rematch/models/monitoringDashboard/model-state.ts
kun-frontend/src/services/monitoring-dashboard/index.ts

some optimizations

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/components/ConfirmBackfillCreateModal/ConfirmBackfillCreateModal.tsx
kun-frontend/src/pages/data-development/index.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/Header.tsx

Feature: task defination add backfill

---

kun-frontend/src/components/Monitoring/DailyTaskFinishLineChart/DailyTaskFinishBarChart.tsx
kun-frontend/src/pages/monitoring-dashboard/components/data-development-board/DailyTaskFinishCountChart.tsx
kun-frontend/src/pages/monitoring-dashboard/components/data-development-board/DailyTaskFinishCountTable.less
kun-frontend/src/pages/monitoring-dashboard/components/data-development-board/DailyTaskFinishCountTable.tsx
kun-frontend/src/pages/monitoring-dashboard/components/data-development-board/DataDevelopmentBoard.tsx
kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/FailedTestCasesTable.less
kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/FailedTestCasesTable.tsx
kun-frontend/src/rematch/models/monitoringDashboard/effects.ts
kun-frontend/src/rematch/models/monitoringDashboard/reducers.ts
kun-frontend/src/services/monitoring-dashboard/index.ts

Feature: update bar chart

---

kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/FailedTestCasesTable.tsx

Feature: glossary add filter

---

kun-frontend/src/pages/data-development/task-definition-config/components/ScheduingConfig.tsx

feature: scheduleConfig add default value

---

kun-frontend/package.json
kun-frontend/src/components/CodeEditor/DefaultMonacoEditor.tsx
kun-frontend/src/components/CodeEditor/MonacoEditorThemeSelect.component.tsx
kun-frontend/yarn.lock

feature: kun-337

---

kun-frontend/src/pages/data-development/components/TaskTemplateCreateDropMenu/TaskTemplateCreateDropMenu.tsx

Fix: commd + a open new link

---

kun-frontend/package.json
kun-frontend/src/components/CodeEditor/CodeEditor.less
kun-frontend/src/components/CodeEditor/DefaultMonacoEditor.tsx
kun-frontend/yarn.lock

Feature: add cursor position

---

kun-frontend/src/pages/data-development/components/AddToOtherViewModal/AddToOtherViewModal.tsx

Fix: view search

---

kun-frontend/src/pages/data-development/components/TaskTemplateCreateDropMenu/TaskTemplateCreateDropMenu.module.less
kun-frontend/src/pages/data-development/components/TaskTemplateCreateDropMenu/TaskTemplateCreateDropMenu.tsx

Feature: add filter for create task 

---

kun-frontend/src/components/PollingLogViewer/PollingLogViewer.less
kun-frontend/src/components/PollingLogViewer/PollingLogViewer.tsx

Fix:fix overflow

---

kun-frontend/src/utils/datetime-utils.ts

Fix:fix dateFormatter

---

kun-frontend/src/utils/datetime-utils.ts

Fix: fix code confluence

---

kun-frontend/src/components/DAGGraph/DAGTaskNode.tsx
kun-frontend/src/pages/operation-center/deployed-task-detail/components/TaskRunDAG.tsx

Feature: optimization Dag

---

kun-frontend/src/pages/dataset/dataset-detail/components/AddDataQualityModal/AddDataQualityModal.tsx
kun-frontend/src/pages/dataset/dataset-detail/components/ValidateRule/ValidateRule.tsx
kun-frontend/src/services/dataQuality.ts

Feature: add rule validate

---

kun-data-discovery/src/main/java/com/miotech/kun/datadiscovery/controller/LineageController.java
kun-data-discovery/src/main/java/com/miotech/kun/datadiscovery/service/LineageAppService.java
kun-data-discovery/src/test/java/com/miotech/kun/datadiscovery/testing/DiscoveryTestBase.java
kun-data-discovery/src/test/java/com/miotech/kun/datadiscovery/testing/LineageAppServiceTest.java
kun-data-discovery/src/test/java/com/miotech/kun/datadiscovery/testing/mockdata/MockWorkFlowClientDataFactory.java
kun-data-discovery/src/test/resources/application-test.yaml
kun-db-schema/kun-infra-db-schema/src/main/resources/kun-infra/V11_create_index.sql

Kun357   增加测试类  

---

kun-frontend/src/pages/glossary/glossary-detail/components/AssetAutoSuggest/AssetAutoSuggest.tsx

Feature: delete database and datasource

---

kun-frontend/src/definitions/Dataset.type.ts
kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/dataset/index.tsx

Feature: add new column

---

kun-frontend/src/pages/glossary/components/GlossaryTree/GlossaryTree.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.tsx

Feature: update parent while change node

---

kun-frontend/src/pages/dataset/index.tsx

Feature: add column fixed

---

kun-frontend/src/pages/glossary/components/GlossaryTree/GlossaryTree.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.less
kun-frontend/src/pages/glossary/glossary-detail/index.tsx
kun-frontend/src/rematch/models/glossary.ts

Feature: node can close and add path

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/monitoring-dashboard/components/data-development-board/TaskDetailsTable.tsx
kun-frontend/src/services/monitoring-dashboard/index.ts

Feature: add failedtask column

---

kun-frontend/src/pages/glossary/glossary-detail/components/AssetAutoSuggest/AssetAutoSuggest.tsx

Fix: fix bug

---

kun-frontend/src/pages/data-development/components/FilterToolbar/TaskDefinitionFilterToolbar.tsx

Fix: set pageNum = 1 while change filter

---

kun-frontend/src/pages/data-development/task-definition-config/components/Header.less

Fix: show complete task name

---

kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.tsx
kun-frontend/src/services/glossary.ts

Feature: add currentId while query parent node

---

kun-frontend/src/components/DAGGraph/DAGTaskNode.tsx
kun-frontend/src/components/Monitoring/DailyTaskFinishLineChart/DailyTaskFinishBarChart.tsx
kun-frontend/src/components/StatusText/StatusText.less
kun-frontend/src/constants/colorConfig.ts
kun-frontend/src/pages/operation-center/backfill-tasks/backfill-tasks-detail/BackfillDetailView.tsx
kun-frontend/src/pages/operation-center/backfill-tasks/components/BackfillTaskRunsSubTable.tsx
kun-frontend/src/pages/operation-center/running-statistics/components/Gantt.less
kun-frontend/src/pages/operation-center/running-statistics/components/ViewFilters.less
kun-frontend/src/styles/variables.less

Feature: task status color unified

---

kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.less
kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.tsx
kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.less
kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.tsx
kun-frontend/src/rematch/models/glossary.ts
kun-frontend/src/services/glossary.ts

Feature: edit glossary search style

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/dataset/index.tsx
kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.tsx
kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.tsx
kun-frontend/src/rematch/models/dataDiscovery.ts
kun-frontend/src/services/glossary.ts

Fix:fix bug

---

kun-frontend/src/pages/glossary/components/GlossaryTree/GlossaryTree.tsx
kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.tsx
kun-frontend/src/rematch/models/glossary.ts

Feature: optimize glossary

---

kun-frontend/src/pages/dataset/index.tsx
kun-frontend/src/rematch/models/dataDiscovery.ts

Feature: edit universal search

---

kun-frontend/src/pages/operation-center/running-statistics/components/Gantt.tsx

Feature: update gantt

---

kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.less
kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.tsx
kun-frontend/src/pages/glossary/components/GlossaryTree/GlossaryTree.tsx
kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.less
kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.tsx
kun-frontend/src/pages/glossary/index.tsx
kun-frontend/src/rematch/models/glossary.ts

Feature: glossary query res add path

---

kun-frontend/src/definitions/TaskDefinition.type.ts
kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/task-definition-config/components/ScheduingConfig.tsx

Feature: add executorLabel

---

kun-frontend/src/pages/data-development/components/TaskViewsAside/TaskViewsAside.tsx
kun-frontend/src/services/data-development/task-definitions.ts

Feature: edit  searchTaskDefinition query

---

kun-frontend/src/components/UserSelect/UserSelect.tsx
kun-frontend/src/components/UsernameText/UsernameText.tsx
kun-frontend/src/definitions/TaskDefinition.type.ts
kun-frontend/src/definitions/TaskDefinitionView.type.ts
kun-frontend/src/pages/data-development/components/DAGNodeInfoDrawer/DAGNodeInfoDrawer.tsx
kun-frontend/src/pages/data-development/components/FilterToolbar/TaskDefinitionFilterToolbar.tsx
kun-frontend/src/pages/data-development/components/TaskDefinitionTable/TaskDefinitionTable.tsx
kun-frontend/src/pages/data-development/components/TaskViewsAside/TaskViewsAside.tsx
kun-frontend/src/pages/data-development/index.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/DiffVersion.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/Header.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/VersionHisotry.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/ViewVersion.tsx
kun-frontend/src/pages/operation-center/backfill-tasks/backfill-tasks-detail/BackfillDetailView.tsx
kun-frontend/src/pages/operation-center/backfill-tasks/components/BackfillTable.tsx
kun-frontend/src/pages/operation-center/backfill-tasks/components/ViewFilters.tsx
kun-frontend/src/pages/operation-center/backfill-tasks/index.tsx
kun-frontend/src/pages/operation-center/scheduled-tasks/components/DeployedTasksTable.tsx
kun-frontend/src/pages/operation-center/scheduled-tasks/index.tsx
kun-frontend/src/rematch/models/dataDevelopment/model-state.ts
kun-frontend/src/rematch/models/operationCenter/backfillTasks/model-state.ts
kun-frontend/src/rematch/models/operationCenter/scheduledTasks/effects.ts
kun-frontend/src/rematch/models/operationCenter/scheduledTasks/model-state.ts
kun-frontend/src/rematch/models/user.ts
kun-frontend/src/services/data-backfill/backfill.services.ts
kun-frontend/src/services/data-development/task-definition-views.ts
kun-frontend/src/services/data-development/task-definitions.ts
kun-frontend/src/services/task-deployments/deployed-tasks.ts

edit username

---

kun-frontend/src/definitions/TaskDefinitionView.type.ts
kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/components/TaskDAG/TaskDAGViewWrapper.tsx
kun-frontend/src/pages/data-development/components/TaskViewsAside/TaskViewsAside.tsx
kun-frontend/src/pages/data-development/index.tsx
kun-frontend/src/rematch/models/dataDevelopment/model-state.ts
kun-frontend/src/rematch/models/dataDevelopment/reducers.ts
kun-frontend/src/services/data-development/task-definition-views.ts

Feature: add dangling tasks

---

kun-frontend/package.json
kun-frontend/src/definitions/Glossary.type.ts
kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.less
kun-frontend/src/pages/glossary/components/DisplayTypeSwitch/index.less
kun-frontend/src/pages/glossary/components/DisplayTypeSwitch/index.tsx
kun-frontend/src/pages/glossary/components/GlossaryTree/GlossaryTree.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.tsx
kun-frontend/src/pages/glossary/glossary-list/TreeList.less
kun-frontend/src/pages/glossary/glossary-list/TreeList.tsx
kun-frontend/src/pages/glossary/glossary-list/index.less
kun-frontend/src/pages/glossary/glossary-list/index.tsx
kun-frontend/src/pages/glossary/index.less
kun-frontend/src/pages/glossary/index.tsx
kun-frontend/src/pages/operation-center/running-statistics/components/Gantt.less
kun-frontend/src/pages/operation-center/running-statistics/components/Gantt.tsx
kun-frontend/src/rematch/models/glossary.ts
kun-frontend/src/rematch/models/glossary/glossaryList.ts
kun-frontend/src/rematch/models/index.ts

Feature: add glossary list view

---

kun-data-platform/kun-data-platform-web/src/main/java/com/miotech/kun/dataplatform/web/controller/DeployedTaskController.java
kun-operation-record/kun-operation-record-common/src/main/java/com/miotech/kun/operationrecord/common/model/OperationRecordType.java
kun-workflow/kun-workflow-client/src/main/java/com/miotech/kun/workflow/client/DefaultWorkflowClient.java
kun-workflow/kun-workflow-client/src/main/java/com/miotech/kun/workflow/client/WorkflowApi.java
kun-workflow/kun-workflow-client/src/main/java/com/miotech/kun/workflow/client/WorkflowClient.java
kun-workflow/kun-workflow-client/src/test/java/com/miotech/kun/workflow/client/WorkflowApiTest.java
kun-workflow/kun-workflow-common/src/main/java/com/miotech/kun/workflow/common/taskrun/service/TaskRunService.java
kun-workflow/kun-workflow-common/src/main/java/com/miotech/kun/workflow/common/taskrun/state/TaskRunAborted.java
kun-workflow/kun-workflow-common/src/main/java/com/miotech/kun/workflow/common/taskrun/state/TaskRunBlocked.java
kun-workflow/kun-workflow-common/src/main/java/com/miotech/kun/workflow/common/taskrun/state/TaskRunCheckFailed.java
kun-workflow/kun-workflow-common/src/main/java/com/miotech/kun/workflow/common/taskrun/state/TaskRunCreated.java
kun-workflow/kun-workflow-common/src/main/java/com/miotech/kun/workflow/common/taskrun/state/TaskRunFailed.java
kun-workflow/kun-workflow-common/src/test/java/com/miotech/kun/workflow/common/taskrun/service/TaskRunServiceTest.java
kun-workflow/kun-workflow-core/src/main/java/com/miotech/kun/workflow/core/Scheduler.java
kun-workflow/kun-workflow-core/src/main/java/com/miotech/kun/workflow/core/event/TaskRunTransitionEventType.java
kun-workflow/kun-workflow-core/src/main/java/com/miotech/kun/workflow/core/model/taskrun/BasicTaskRunState.java
kun-workflow/kun-workflow-core/src/main/java/com/miotech/kun/workflow/core/model/taskrun/TaskRunStatus.java
kun-workflow/kun-workflow-scheduler/src/main/java/com/miotech/kun/workflow/LocalScheduler.java
kun-workflow/kun-workflow-scheduler/src/main/java/com/miotech/kun/workflow/TaskRunStateMachine.java
kun-workflow/kun-workflow-scheduler/src/main/java/com/miotech/kun/workflow/scheduler/TaskManager.java
kun-workflow/kun-workflow-scheduler/src/test/java/com/miotech/kun/workflow/scheduler/TaskManagerTest.java
kun-workflow/kun-workflow-web/src/main/java/com/miotech/kun/workflow/web/controller/TaskRunController.java

skip taskrun

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/glossary/glossary-detail/components/AssetList/AssetList.less
kun-frontend/src/pages/glossary/glossary-detail/components/AssetList/AssetList.tsx
kun-frontend/src/pages/glossary/glossary-list/TreeList.less
kun-frontend/src/pages/glossary/glossary-list/TreeList.tsx
kun-frontend/src/pages/operation-center/deployed-task-detail/components/TaskRunsTable.tsx
kun-frontend/src/rematch/models/glossary.ts
kun-frontend/src/services/task-deployments/deployed-tasks.ts

Feature: add task skip

---

kun-frontend/src/pages/dataset/dataset-detail/index.less
kun-frontend/src/pages/dataset/dataset-detail/index.tsx
kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.tsx
kun-frontend/src/pages/glossary/glossary-list/index.tsx
kun-frontend/src/pages/glossary/index.tsx
kun-frontend/src/services/glossary.ts

Feature: dataset detail page can add glossary

---

kun-frontend/src/pages/dataset/dataset-detail/index.less
kun-frontend/src/pages/dataset/dataset-detail/index.tsx
kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.less
kun-frontend/src/pages/glossary/components/AutosuggestInput/AutosuggestInput.tsx
kun-frontend/src/pages/glossary/glossary-detail/components/AssetList/AssetList.less
kun-frontend/src/pages/glossary/glossary-detail/components/ParentSearch/ParentSearch.tsx
kun-frontend/src/pages/glossary/glossary-detail/index.tsx
kun-frontend/src/pages/glossary/glossary-list/TreeList.tsx
kun-frontend/src/pages/glossary/glossary-list/index.tsx
kun-frontend/src/pages/glossary/index.tsx

Fix: fix glossary bug

---

kun-frontend/src/components/PollingLogViewer/PollingLogViewer.tsx

Fix: fix log search

---

kun-frontend/package.json
kun-frontend/src/components/PollingLogViewer/PollingLogViewer.tsx
kun-frontend/yarn.lock

Fix: fix log bug

---

kun-frontend/src/pages/operation-center/backfill-tasks/components/BackfillInstanceLogViewer.tsx

Fix: fix log download bug

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/task-definition-config/components/NotificationConfig.tsx

Feature: add description for  sla level config

---

kun-frontend/src/pages/data-development/task-definition-config/components/BodyForm.less
kun-frontend/src/pages/data-development/task-definition-config/components/NotificationConfig.tsx

Feature: edit sla option

---

kun-frontend/src/pages/operation-center/backfill-tasks/components/BackfillTaskRunsSubTable.tsx

Fix: fix copy bug

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/operation-center/deployed-task-detail/components/TaskAttemptDetail.tsx
kun-frontend/src/pages/operation-center/deployed-task-detail/index.tsx
kun-frontend/src/pages/operation-center/scheduled-tasks/components/RightPanel.tsx

Feature: add link to Gantt Chart

---

kun-frontend/src/definitions/TaskDefinition.type.ts
kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/task-definition-config/components/ScheduingConfig.tsx
kun-frontend/src/services/data-development/task-definitions.ts

Feature: add executorLabel and queueName

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/task-definition-config/components/DiffVersion.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/VersionHisotry.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/ViewVersion.tsx

Feature: add view configration

---

kun-frontend/src/pages/operation-center/running-statistics/components/WaitTask.less

Fix: fix style

---

kun-frontend/src/definitions/Gantt.type.ts
kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/operation-center/running-statistics/components/Gantt.tsx
kun-frontend/src/pages/operation-center/running-statistics/components/TooltipHtml.less
kun-frontend/src/pages/operation-center/running-statistics/components/WaitTask.less
kun-frontend/src/pages/operation-center/running-statistics/components/WaitTask.tsx
kun-frontend/src/pages/operation-center/running-statistics/index.tsx

Feature: optimize gantt wait task

---

kun-frontend/src/pages/dataset/dataset-detail/index.tsx
kun-frontend/src/rematch/models/datasetDetail.ts

Fix: Front-end paging instead of back-end paging

---

kun-frontend/config/routes.ts
kun-frontend/src/layouts/index.tsx
kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/login/OAuth.tsx
kun-frontend/src/pages/login/index.less
kun-frontend/src/pages/login/index.tsx
kun-frontend/src/services/user.ts

Feature: add OAuth login

---

kun-frontend/src/components/DAGGraph/DAGTaskGraph.tsx
kun-frontend/src/components/DAGGraph/DAGTaskNode.less
kun-frontend/src/components/DAGGraph/DAGTaskNode.tsx
kun-frontend/src/components/LineageDiagram/DatasetNodeCard/CardPort.tsx
kun-frontend/src/pages/operation-center/deployed-task-detail/components/TaskRunDAG.tsx
kun-frontend/src/pages/operation-center/scheduled-tasks/components/DeployedTaskDAG.tsx
kun-frontend/src/pages/operation-center/scheduled-tasks/index.tsx
kun-frontend/src/rematch/models/dag.ts
kun-frontend/src/rematch/models/index.ts

Feature: optimize dag

---

kun-frontend/src/components/DAGGraph/index.less
kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/task-definition-config/components/BodyForm.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/task-dag/index.tsx

Feature: add task definition DAG

---

kun-frontend/src/locales/en-US.ts
kun-frontend/src/locales/zh-CN.ts
kun-frontend/src/pages/data-development/task-definition-config/components/BodyForm.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/Header.tsx
kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/TestCaseRuleTable.tsx

Fix: fix task definition request dag

---

kun-frontend/src/pages/monitoring-dashboard/components/data-discovery-board/TestCaseRuleTable.tsx
kun-frontend/src/pages/operation-center/deployed-task-detail/index.tsx
kun-frontend/src/rematch/models/operationCenter/deployedTaskDetail/effects.ts

Feature: add locate taskrun

---

kun-frontend/src/pages/data-settings/components/AddUpdateDatabaseModal/AddUpdateDatabaseModal.tsx
kun-frontend/src/pages/data-settings/components/DatabaseItem/DatabaseItem.tsx
kun-frontend/src/pages/data-settings/index.tsx
kun-frontend/src/rematch/models/dataSettings.ts
kun-frontend/src/services/dataSettings.ts

Feature: delete databasetype request

---

kun-commons/kun-commons-query/src/main/java/com/miotech/kun/commons/query/datasource/DataSourceType.java
kun-commons/kun-commons-query/src/main/java/com/miotech/kun/commons/query/persistence/MetadataRepository.java
kun-commons/kun-commons-query/src/main/java/com/miotech/kun/commons/query/utils/URLUtils.java
kun-commons/kun-commons-testing/src/main/java/com/miotech/kun/commons/testing/DatabaseTestBase.java
kun-data-discovery/src/main/java/com/miotech/kun/datadiscovery/controller/DataSourceController.java
kun-data-discovery/src/main/java/com/miotech/kun/datadiscovery/model/entity/DataSourceVO.java
kun-data-discovery/src/main/java/com/miotech/kun/datadiscovery/service/DataSourceService.java
kun-data-discovery/src/main/java/com/miotech/kun/datadiscovery/service/MetadataService.java
kun-data-quality/kun-data-quality-web/src/main/java/com/miotech/kun/dataquality/web/persistence/DatasetRepository.java
kun-data-quality/kun-data-quality-web/src/main/java/com/miotech/kun/dataquality/web/utils/Constants.java
kun-data-quality/kun-data-quality-web/src/test/java/com/miotech/kun/dataquality/service/DataQualityServiceTest.java
kun-data-quality/kun-data-quality-web/src/test/java/com/miotech/kun/dataquality/util/SQLValidatorTest.java
kun-db-schema/kun-infra-db-schema/src/main/resources/kun-infra/V19__remove_datasource_type_table.sql
kun-metadata/kun-metadata-common/src/main/java/com/miotech/kun/metadata/common/dao/DataSourceDao.java
kun-metadata/kun-metadata-common/src/main/java/com/miotech/kun/metadata/common/service/DataSourceService.java
kun-metadata/kun-metadata-core/src/main/java/com/miotech/kun/metadata/core/model/datasource/DataSource.java
kun-metadata/kun-metadata-core/src/main/java/com/miotech/kun/metadata/core/model/vo/DatasourceTemplate.java
kun-metadata/kun-metadata-databuilder/src/test/java/com/miotech/kun/metadata/databuilder/TestContainerBuilder.java
kun-metadata/kun-metadata-web/src/main/java/com/miotech/kun/metadata/web/controller/DataSourceController.java

Reverts miotech/kun-scheduler#1049

Revert "datasouce type Refactoring"

---

kun-frontend/src/components/DAGGraph/DAGTaskNode.tsx
kun-frontend/src/components/TextContainer/TextContainer.tsx
kun-frontend/src/pages/operation-center/deployed-task-detail/components/TaskRunsTable.tsx
kun-frontend/src/pages/operation-center/deployed-task-detail/components/UpstreamFailed.tsx

Feature: taskRunsTable add upstreamFailedTaskRuns popover

---

kun-frontend/src/pages/operation-center/running-statistics/components/BarRender.tsx

Fix: fix time duration bug

---

kun-frontend/src/components/DAGGraph/DAGTaskGraph.tsx
kun-frontend/src/components/KeyValueTable/KeyValueTable.less
kun-frontend/src/components/KeyValueTable/KeyValueTable.tsx
kun-frontend/src/pages/data-development/task-definition-config/components/DiffVersion.tsx
kun-frontend/src/pages/operation-center/running-statistics/components/BarRender.less
kun-frontend/src/pages/operation-center/running-statistics/components/Gantt.tsx

Feature: add dag fullscreen and copy for task config

---

kun-frontend/src/pages/operation-center/running-statistics/components/BarRender.tsx
kun-frontend/src/pages/operation-center/running-statistics/components/Gantt.tsx

Feature:edit created task position for gantt chart
